### ISSUE TITLE
0.0.3 crash - TypeError: get_one_x_coverage_of_kmers() missing 3 required positional arguments: 'sequence', 'k', and 'end'

### ISSUE THREAD

**Issue by tseemann** [andrewjpage/plasmidpredictor#8]
```
plasmidpredictor --verbose subreads.fq.gz

GENE    COMPLETENESS    %COVERAGE       ACCESSION       DATABASE        PRODUCT
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/plasmidpredictor", line 53, in <module>
    plasmidpredictor.run()
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.6/site-packages/plasmidpredictor/PlasmidPredictor.py", line 49, in run
    fastq.read_filter_and_map()
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.6/site-packages/plasmidpredictor/Fastq.py", line 52, in read_filter_and_map
    if self.map_read(read):
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.6/site-packages/plasmidpredictor/Fastq.py", line 66, in map_read
    candidate_gene_names = self.does_read_contain_quick_pass_kmers(read.seq)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.6/site-packages/plasmidpredictor/Fastq.py", line 81, in does_read_contain_quick_pass_kmers
    read_onex_kmers = kmers_obj.get_one_x_coverage_of_kmers()
TypeError: get_one_x_coverage_of_kmers() missing 3 required positional arguments: 'sequence', 'k', and 'end'
```

**Comment by andrewjpage** [comment]
fixed
